version: '3.2'
services:
  tests:
    build:
      context: tests
      dockerfile: Dockerfile
    # command: ["bash", "-c" ,"export"]
    depends_on:
      - app
    environment:
      - API_URL=http://app:5000
    volumes:
      # - type: volume
      #   source: ./uploads
      #   target: /app/wwwroot
        # volume:
        #   nocopy: true  
      - type: bind
        source: ./uploads
        target: /app/wwwroot
      # - type: bind
      #   source: ./uploads
      #   target: /wwwroot
      # - ./uploads:/app/wwwroot
  app:
    # image: guneysu/imageserver:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000

volumes:
  uploads: