version: '3'
services:
  imageserver:
    build:
      context: tests
      dockerfile: Dockerfile
    depends_on:
      - app

  app:
    image: guneysu/imageserver:latest
    ports:
      - 5000:5000
